@startuml
title インスタグラムFFチェッカー シーケンス図
ユーザ -> アプリケーション: 調べたいアカウントのIDを伴なったリクエスト
アプリケーション -> バックエンド: IDについての情報をリクエスト
バックエンド -> Instagram: IDのアカウントの現在のフォロワーリストを閲覧
Instagram -> バックエンド: IDのアカウントについてのデータを渡す
バックエンド --> アプリケーション: (IDのアカウントのデータが存在しなかった場合)\n指定されたIDが存在しなかったことを報せる
アプリケーション --> ユーザ:(IDのアカウントのデータが存在しなかった場合)\n指定されたIDが存在しなかったことを表示する
バックエンド -> DB: 最新のフォロワーリストと共に\nIDのアカウントのフォロワーリストをリクエスト
DB -> バックエンド: 過去のフォロワーリストについてのログを返す
DB -> DB: IDのフォロワーリストに最新のリストを追加する
バックエンド -> アプリケーション: ・フォロワー増減の変遷\n・直近の増減\nを返す
アプリケーション -> ユーザ: ・フォロワー増減の変遷\n・直近の増減\nをグラフ化して表示
@enduml